# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CustomiseEditorWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(438, 82)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.CE_FontSizeLabel = QtWidgets.QLabel(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CE_FontSizeLabel.sizePolicy().hasHeightForWidth())
        self.CE_FontSizeLabel.setSizePolicy(sizePolicy)
        self.CE_FontSizeLabel.setObjectName("CE_FontSizeLabel")
        self.gridLayout.addWidget(self.CE_FontSizeLabel, 0, 0, 1, 1)
        self.CE_FontSizeSpinBox = QtWidgets.QSpinBox(Dialog)
        self.CE_FontSizeSpinBox.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CE_FontSizeSpinBox.sizePolicy().hasHeightForWidth())
        self.CE_FontSizeSpinBox.setSizePolicy(sizePolicy)
        self.CE_FontSizeSpinBox.setMinimumSize(QtCore.QSize(0, 0))
        self.CE_FontSizeSpinBox.setSizeIncrement(QtCore.QSize(0, 0))
        self.CE_FontSizeSpinBox.setBaseSize(QtCore.QSize(0, 0))
        self.CE_FontSizeSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.CE_FontSizeSpinBox.setMinimum(8)
        self.CE_FontSizeSpinBox.setMaximum(72)
        self.CE_FontSizeSpinBox.setObjectName("CE_FontSizeSpinBox")
        self.gridLayout.addWidget(self.CE_FontSizeSpinBox, 0, 1, 1, 1)
        self.CE_FontSizeHSlider = QtWidgets.QSlider(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CE_FontSizeHSlider.sizePolicy().hasHeightForWidth())
        self.CE_FontSizeHSlider.setSizePolicy(sizePolicy)
        self.CE_FontSizeHSlider.setMinimum(8)
        self.CE_FontSizeHSlider.setMaximum(72)
        self.CE_FontSizeHSlider.setOrientation(QtCore.Qt.Horizontal)
        self.CE_FontSizeHSlider.setObjectName("CE_FontSizeHSlider")
        self.gridLayout.addWidget(self.CE_FontSizeHSlider, 0, 2, 1, 1)
        self.CE_IndentSizeLabel = QtWidgets.QLabel(Dialog)
        self.CE_IndentSizeLabel.setObjectName("CE_IndentSizeLabel")
        self.gridLayout.addWidget(self.CE_IndentSizeLabel, 1, 0, 1, 1)
        self.CE_IndentSizeSpinBox = QtWidgets.QSpinBox(Dialog)
        self.CE_IndentSizeSpinBox.setButtonSymbols(QtWidgets.QAbstractSpinBox.PlusMinus)
        self.CE_IndentSizeSpinBox.setMinimum(2)
        self.CE_IndentSizeSpinBox.setMaximum(10)
        self.CE_IndentSizeSpinBox.setObjectName("CE_IndentSizeSpinBox")
        self.gridLayout.addWidget(self.CE_IndentSizeSpinBox, 1, 1, 1, 1)
        self.CE_IndentSizeHSlider = QtWidgets.QSlider(Dialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CE_IndentSizeHSlider.sizePolicy().hasHeightForWidth())
        self.CE_IndentSizeHSlider.setSizePolicy(sizePolicy)
        self.CE_IndentSizeHSlider.setMinimum(2)
        self.CE_IndentSizeHSlider.setMaximum(10)
        self.CE_IndentSizeHSlider.setOrientation(QtCore.Qt.Horizontal)
        self.CE_IndentSizeHSlider.setObjectName("CE_IndentSizeHSlider")
        self.gridLayout.addWidget(self.CE_IndentSizeHSlider, 1, 2, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.CE_FontSizeLabel.setText(_translate("Dialog", "Font size"))
        self.CE_FontSizeSpinBox.setSuffix(_translate("Dialog", " pt"))
        self.CE_IndentSizeLabel.setText(_translate("Dialog", "Indent size"))
        self.CE_IndentSizeSpinBox.setSuffix(_translate("Dialog", " spaces"))
