# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ViewBlock.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(595, 422)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.VB_GroupBox = QtWidgets.QGroupBox(Dialog)
        self.VB_GroupBox.setObjectName("VB_GroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.VB_GroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.VB_BlockWidget = QtWidgets.QPlainTextEdit(self.VB_GroupBox)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.VB_BlockWidget.setFont(font)
        self.VB_BlockWidget.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.VB_BlockWidget.setObjectName("VB_BlockWidget")
        self.gridLayout.addWidget(self.VB_BlockWidget, 0, 0, 1, 1)
        self.horizontalLayout.addWidget(self.VB_GroupBox)
        self.VB_ButtonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.VB_ButtonBox.setOrientation(QtCore.Qt.Vertical)
        self.VB_ButtonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Ok)
        self.VB_ButtonBox.setObjectName("VB_ButtonBox")
        self.horizontalLayout.addWidget(self.VB_ButtonBox)

        self.retranslateUi(Dialog)
        self.VB_ButtonBox.accepted.connect(Dialog.accept) # type: ignore
        self.VB_ButtonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "View block"))
        self.VB_GroupBox.setTitle(_translate("Dialog", "View block"))
        self.VB_BlockWidget.setPlaceholderText(_translate("Dialog", "No block"))
