# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CPG_ColourPicker.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CPG_CP_IncompleteWidget(object):
    def setupUi(self, CPG_CP_IncompleteWidget):
        CPG_CP_IncompleteWidget.setObjectName("CPG_CP_IncompleteWidget")
        CPG_CP_IncompleteWidget.resize(407, 449)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CPG_CP_IncompleteWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CPG_CP_Colour = QtWidgets.QLabel(CPG_CP_IncompleteWidget)
        self.CPG_CP_Colour.setText("")
        self.CPG_CP_Colour.setObjectName("CPG_CP_Colour")
        self.horizontalLayout.addWidget(self.CPG_CP_Colour)

        self.retranslateUi(CPG_CP_IncompleteWidget)
        QtCore.QMetaObject.connectSlotsByName(CPG_CP_IncompleteWidget)

    def retranslateUi(self, CPG_CP_IncompleteWidget):
        _translate = QtCore.QCoreApplication.translate
        CPG_CP_IncompleteWidget.setWindowTitle(_translate("CPG_CP_IncompleteWidget", "Form"))
