# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/CPG_Main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(956, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.CPG_CentralLayout = QtWidgets.QWidget(MainWindow)
        self.CPG_CentralLayout.setObjectName("CPG_CentralLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.CPG_CentralLayout)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.CPG_TopHoriLayout = QtWidgets.QHBoxLayout()
        self.CPG_TopHoriLayout.setObjectName("CPG_TopHoriLayout")
        self.CPG_PrgTitleLabel = QtWidgets.QLabel(self.CPG_CentralLayout)
        self.CPG_PrgTitleLabel.setTextFormat(QtCore.Qt.MarkdownText)
        self.CPG_PrgTitleLabel.setObjectName("CPG_PrgTitleLabel")
        self.CPG_TopHoriLayout.addWidget(self.CPG_PrgTitleLabel)
        self.CPG_CreditsLabel = QtWidgets.QLabel(self.CPG_CentralLayout)
        self.CPG_CreditsLabel.setTextFormat(QtCore.Qt.RichText)
        self.CPG_CreditsLabel.setObjectName("CPG_CreditsLabel")
        self.CPG_TopHoriLayout.addWidget(self.CPG_CreditsLabel)
        self.CPG_StatusLayout = QtWidgets.QGridLayout()
        self.CPG_StatusLayout.setObjectName("CPG_StatusLayout")
        self.CPG_LeaderboardButton = QtWidgets.QPushButton(self.CPG_CentralLayout)
        self.CPG_LeaderboardButton.setObjectName("CPG_LeaderboardButton")
        self.CPG_StatusLayout.addWidget(self.CPG_LeaderboardButton, 0, 2, 1, 1)
        self.CPG_NewGameButton = QtWidgets.QPushButton(self.CPG_CentralLayout)
        self.CPG_NewGameButton.setObjectName("CPG_NewGameButton")
        self.CPG_StatusLayout.addWidget(self.CPG_NewGameButton, 0, 0, 1, 1)
        self.CPG_PlayerScoreLayout = QtWidgets.QHBoxLayout()
        self.CPG_PlayerScoreLayout.setObjectName("CPG_PlayerScoreLayout")
        self.CPG_PlayerScoreLabel = QtWidgets.QLabel(self.CPG_CentralLayout)
        self.CPG_PlayerScoreLabel.setObjectName("CPG_PlayerScoreLabel")
        self.CPG_PlayerScoreLayout.addWidget(self.CPG_PlayerScoreLabel)
        self.CPG_PlayerScoreVertLine = QtWidgets.QFrame(self.CPG_CentralLayout)
        self.CPG_PlayerScoreVertLine.setFrameShape(QtWidgets.QFrame.VLine)
        self.CPG_PlayerScoreVertLine.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.CPG_PlayerScoreVertLine.setObjectName("CPG_PlayerScoreVertLine")
        self.CPG_PlayerScoreLayout.addWidget(self.CPG_PlayerScoreVertLine)
        self.CPG_StatusLayout.addLayout(self.CPG_PlayerScoreLayout, 1, 0, 1, 1)
        self.CPG_TimeLabel = QtWidgets.QLabel(self.CPG_CentralLayout)
        self.CPG_TimeLabel.setObjectName("CPG_TimeLabel")
        self.CPG_StatusLayout.addWidget(self.CPG_TimeLabel, 1, 2, 1, 1)
        self.CPG_TopHoriLayout.addLayout(self.CPG_StatusLayout)
        self.verticalLayout_2.addLayout(self.CPG_TopHoriLayout)
        self.CPG_StackedWidget = QtWidgets.QStackedWidget(self.CPG_CentralLayout)
        self.CPG_StackedWidget.setObjectName("CPG_StackedWidget")
        self.MainGame = QtWidgets.QWidget()
        self.MainGame.setObjectName("MainGame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.MainGame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CPG_ColourPickerFrame = QtWidgets.QFrame(self.MainGame)
        self.CPG_ColourPickerFrame.setFrameShape(QtWidgets.QFrame.Box)
        self.CPG_ColourPickerFrame.setFrameShadow(QtWidgets.QFrame.Plain)
        self.CPG_ColourPickerFrame.setLineWidth(2)
        self.CPG_ColourPickerFrame.setMidLineWidth(0)
        self.CPG_ColourPickerFrame.setObjectName("CPG_ColourPickerFrame")
        self.horizontalLayout.addWidget(self.CPG_ColourPickerFrame)
        self.CPG_StackedWidget.addWidget(self.MainGame)
        self.Leaderboard = QtWidgets.QWidget()
        self.Leaderboard.setObjectName("Leaderboard")
        self.CPG_StackedWidget.addWidget(self.Leaderboard)
        self.verticalLayout_2.addWidget(self.CPG_StackedWidget)
        MainWindow.setCentralWidget(self.CPG_CentralLayout)

        self.retranslateUi(MainWindow)
        self.CPG_StackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "The Colour Picker Game"))
        self.CPG_PrgTitleLabel.setText(_translate("MainWindow", "**The colour picker game**"))
        self.CPG_CreditsLabel.setText(_translate("MainWindow", "<html><head/><body><p>Another amazing program brought to you by Katsumi<br/><a href=\"https://x.com/realKatsumi_vn\"><span style=\" text-decoration: underline; color:#0000ff;\">x.com/realKatsumi_vn</span></a></p></body></html>"))
        self.CPG_LeaderboardButton.setText(_translate("MainWindow", "Leaderboard"))
        self.CPG_NewGameButton.setText(_translate("MainWindow", "New game"))
        self.CPG_PlayerScoreLabel.setText(_translate("MainWindow", "<html><head/><body><p>Score: <span style=\" font-weight:600; color:#0a50f3;\">0</span></p></body></html>"))
        self.CPG_TimeLabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" color:#ff0004;\">00:00:00</span></p></body></html>"))
