# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CPG_ColourPicker.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CPG_CP_IncompleteWidget(object):
    def setupUi(self, CPG_CP_IncompleteWidget):
        CPG_CP_IncompleteWidget.setObjectName("CPG_CP_IncompleteWidget")
        CPG_CP_IncompleteWidget.resize(469, 237)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CPG_CP_IncompleteWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.CPG_CP_ColourRect = QtWidgets.QLabel(CPG_CP_IncompleteWidget)
        self.CPG_CP_ColourRect.setText("")
        self.CPG_CP_ColourRect.setObjectName("CPG_CP_ColourRect")
        self.horizontalLayout.addWidget(self.CPG_CP_ColourRect)
        self.CPG_CP_SlidersLayout = QtWidgets.QVBoxLayout()
        self.CPG_CP_SlidersLayout.setContentsMargins(-1, -1, 0, -1)
        self.CPG_CP_SlidersLayout.setObjectName("CPG_CP_SlidersLayout")
        self.CPG_CP_RedChannelDescLabel = QtWidgets.QLabel(CPG_CP_IncompleteWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CPG_CP_RedChannelDescLabel.sizePolicy().hasHeightForWidth())
        self.CPG_CP_RedChannelDescLabel.setSizePolicy(sizePolicy)
        self.CPG_CP_RedChannelDescLabel.setObjectName("CPG_CP_RedChannelDescLabel")
        self.CPG_CP_SlidersLayout.addWidget(self.CPG_CP_RedChannelDescLabel)
        self.CPG_CP_RedChannelSlider = QtWidgets.QSlider(CPG_CP_IncompleteWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CPG_CP_RedChannelSlider.sizePolicy().hasHeightForWidth())
        self.CPG_CP_RedChannelSlider.setSizePolicy(sizePolicy)
        self.CPG_CP_RedChannelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.CPG_CP_RedChannelSlider.setObjectName("CPG_CP_RedChannelSlider")
        self.CPG_CP_SlidersLayout.addWidget(self.CPG_CP_RedChannelSlider)
        self.CPG_CP_GreenChannelDescLabel = QtWidgets.QLabel(CPG_CP_IncompleteWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CPG_CP_GreenChannelDescLabel.sizePolicy().hasHeightForWidth())
        self.CPG_CP_GreenChannelDescLabel.setSizePolicy(sizePolicy)
        self.CPG_CP_GreenChannelDescLabel.setObjectName("CPG_CP_GreenChannelDescLabel")
        self.CPG_CP_SlidersLayout.addWidget(self.CPG_CP_GreenChannelDescLabel)
        self.CPG_CP_GreenChannelSlider = QtWidgets.QSlider(CPG_CP_IncompleteWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CPG_CP_GreenChannelSlider.sizePolicy().hasHeightForWidth())
        self.CPG_CP_GreenChannelSlider.setSizePolicy(sizePolicy)
        self.CPG_CP_GreenChannelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.CPG_CP_GreenChannelSlider.setObjectName("CPG_CP_GreenChannelSlider")
        self.CPG_CP_SlidersLayout.addWidget(self.CPG_CP_GreenChannelSlider)
        self.CPG_CP_BlueChannelDescLabel = QtWidgets.QLabel(CPG_CP_IncompleteWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CPG_CP_BlueChannelDescLabel.sizePolicy().hasHeightForWidth())
        self.CPG_CP_BlueChannelDescLabel.setSizePolicy(sizePolicy)
        self.CPG_CP_BlueChannelDescLabel.setObjectName("CPG_CP_BlueChannelDescLabel")
        self.CPG_CP_SlidersLayout.addWidget(self.CPG_CP_BlueChannelDescLabel)
        self.CPG_CP_BlueChannelSlider = QtWidgets.QSlider(CPG_CP_IncompleteWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.CPG_CP_BlueChannelSlider.sizePolicy().hasHeightForWidth())
        self.CPG_CP_BlueChannelSlider.setSizePolicy(sizePolicy)
        self.CPG_CP_BlueChannelSlider.setOrientation(QtCore.Qt.Horizontal)
        self.CPG_CP_BlueChannelSlider.setObjectName("CPG_CP_BlueChannelSlider")
        self.CPG_CP_SlidersLayout.addWidget(self.CPG_CP_BlueChannelSlider)
        self.horizontalLayout.addLayout(self.CPG_CP_SlidersLayout)

        self.retranslateUi(CPG_CP_IncompleteWidget)
        QtCore.QMetaObject.connectSlotsByName(CPG_CP_IncompleteWidget)

    def retranslateUi(self, CPG_CP_IncompleteWidget):
        _translate = QtCore.QCoreApplication.translate
        CPG_CP_IncompleteWidget.setWindowTitle(_translate("CPG_CP_IncompleteWidget", "Form"))
        self.CPG_CP_RedChannelDescLabel.setText(_translate("CPG_CP_IncompleteWidget", "Red"))
        self.CPG_CP_GreenChannelDescLabel.setText(_translate("CPG_CP_IncompleteWidget", "Green"))
        self.CPG_CP_BlueChannelDescLabel.setText(_translate("CPG_CP_IncompleteWidget", "Blue"))
